### ISSUE TITLE
fetch:{eval} in PHP function no longer works with assigned values from function

### ISSUE THREAD

**Issue by strikernl** [smarty-php/smarty#152]
With Smarty **3.1.21** the following used to work:

```php
require 'smarty-3.1.21/libs/Smarty.class.php';

$s = new Smarty();
$s->registerPlugin('function', 'myTestFunction', 'myTestFunction');
$s->display('test.tpl');

function myTestFunction ($params, $smarty) {
	$smarty->assign('value', $params['testvalue']);
	return $smarty->fetch('eval:' . $params['testhtml']);
}
```

Contents of test.tpl:
```smarty
test value: {myTestFunction testvalue='5' testhtml='"{$value}"'}
```

The output would be as follows:

```
test value: "5"
```

However, the same code with **3.1.29** loaded gives me the following result:

```
test value: ""
```
 
Is this expected behaviour, is there something I am supposed to be doing differently since some version after 3.1.21? Or is this a bug?

**Comment by uwetews** [comment]
The root cause is that in Smarty 3 the 2nd parameter of plugins is the calling template object but not the Smarty object.
Correctly it should be

```php
function myTestFunction ($params, $template) {
    $template->smarty->assign('value', $params['testvalue']);
    return $template->smarty->fetch('eval:' . $params['testhtml']);
}
```

There is a fallback that you can call must methods also on a template object and some link got broken in your example.

The fix is now in the master branch and will late be included in 3.1.30

**Comment by bedandbreakfasteu** [comment]
Great, thanks!

**Comment by strikernl** [comment]
Great, thanks!
