### ISSUE TITLE
Foreach {$item@index} and {$item@iteration} not recognized in a included template

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#189]
Foreach {$item@index} and {$item@iteration} not recognized in a included template:

```
{foreach $last_articles as $item}
    {$item@index}.{$item@iteration}.
    {include 'site/inc/article_item.tpl'}
{/foreach}
```

Here, in the template article_item.tpl I want to use :  {$item@index}.{$item@iteration}, but are not recognized. Data like: {$item.article_title}, {$item.article_text} is recognized.

I use smarty 3.1.30-dev/41

**Comment by uwetews** [comment]
I think 
```php
{foreach $last_articles as $item}
    {$item@index}.{$item@iteration}.
    {include 'site/inc/article_item.tpl'}
{/foreach}
```
does work

but
```php
{foreach $last_articles as $item}
    {include 'site/inc/article_item.tpl'}
{/foreach}
```
does not

Foreach runtime optimization does remove code for properties not used.
However the compiler can only check the current template for used properties.
So in first example  $item.index and $item.iteration are created, but not in the second.

There is now a new attribute 'properties' which does force compilation of properties which might be used outside the current template scope.
```php
{foreach $last_articles as $item, properties=[index,iteration]}
    {include 'site/inc/article_item.tpl'}
{/foreach}
```

read NEW_FEATURES.txt

The fix is now in the master branch

**Comment by ophian** [comment]
> However the compiler can only check the current template for used properties.
> There is now a new attribute 'properties' which does force compilation of properties which might be used outside the current template scope.

If you add this (concerning current and outside scope template) to the new features text it is much clearer, IMHO.
