### ISSUE TITLE
Semantic versioning convention

### ISSUE THREAD

**Issue by pnikolov** [smarty-php/smarty#208]
I find _Smarty_ to be yet the best PHP template engine out there.
 Is there a reason not to follow the _Semantic Versioning_ http://semver.org convention? I think the current release versioning convention introduces a lot of confusion when updating?

**Comment by AnrDaemon** [comment]
What exactly is your issue with Smarty versioning?

**Comment by abeger** [comment]
> What exactly is your issue with Smarty versioning?

The really nice thing about semver is that the version numbers tell users how drastic a change has been made to the codebase:

* 1.2.3 => 1.2.4 means a bugfix has happened
* 1.2 => 1.3 means functionality has been added or changed, but everything is backwards-compatible
* 1 => 2 means _breaking changes_ have been made and code using this library may break if you upgrade

If you follow semver, folks using your library can then set their Composer configs to allow only as much change as they're comfortable with (https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators).

Our team set up our `composer.json` files assuming Smarty used semantic versioning, only allowing for bugfix upgrades (`~3.1.27`). We were caught off-guard when what we _thought_ was a simple bug fix upgrade to 3.1.28 broke multiple systems with a backwards-incompatible change.

Now with the [critical update in 3.1.33](https://github.com/sbaresearch/advisories/tree/public/2018/SBA-ADV-20180420-01_Smarty_Path_Traversal), I need to upgrade as soon as possible. Because of the previous experience,  I'm forced to carefully inspect the changelog and probably do a full retest of my system to make sure that none of the other, non-bugfix changes break anything.

If Smarty were using semver, I could confidently put this change in with a lot less regression testing, knowing that just the critical security issue has been patched.

**Comment by AnrDaemon** [comment]
Smarty was born way before Composer. SemVer, et cetera.
This does not relinquish your responsibility to test any changes you are doing to your project.

**Comment by etherbob** [comment]
Semantic versioning would in no way absolve downstream consumers of the responsibility to test --including bug fixes -- but, were Smarty to introduce SemVer for future updates it would communicate the maintainer's intent for a given release's scope and give us some sense of what to expect going in. (i.e. I'd be unsurprised to need to budget time for major changes to my code base from Smarty 3.1.2x to a hypothetical Smarty 4.0.0, but would expect a jump from 3.1.33 to mostly pass my test suite.)

I get that it's a pretty big change to how Smarty has historically marked it's progress. We had similar debates internally--I was very much opposed--about our various shared libraries, but have greatly appreciated the extra communication of intent being added to our versions. Thank you for your work on this excellent and well loved library and your consideration on this change.

**Comment by abeger** [comment]
To clarify, I wasn't saying that I wouldn't test thoroughly for a bugfix. I meant that with a small release just covering a few bugfixes, the _scope_ of the change and testing can be greatly reduced. 

To illustrate, here's how we tend to handle Rails upgrades: 

When we update Rails by a `0.0.x` increment, it's usually pretty cut & dry: do our regression tests to make sure the patch does what it says, move on. These are upgrades we _need_ to do, often immediately, due to security concerns.

For a Rails `0.x.0` increment, it's pretty much the same, but we're  more careful: the changes tend to be bigger, so we allot more time to test around all of them. Often we update something to use a better feature or address deprecations. These are upgrades that we usually do not long after they come out, just to make sure we're up to date.

For a Rails `x.0.0` release, we plan on several days of upgrading and testing.  We make sure we've repaired every breaking change. We making sure we've regression tested _everything_ to guarantee that we haven't missed any breaks in the library. These are upgrades that we often hold off on until we have the time to do the necessary intense review & testing. 

This predictability about what a library upgrade entails makes ongoing maintenance of our systems more consistent and more confident.

**Comment by wisskid** [comment]
I agree, and I see no reason to not start using semver now.
