### ISSUE TITLE
Performance drop when using modifiers like date_format

### ISSUE THREAD

**Issue by juangacovas** [smarty-php/smarty#280]
Smarty 3.1.30
File: plugins\modifier.date_format.php

Noticed while doing some profiling: for 300 hits to date_format (say, a table with 300 calls to date_format), the code for date_format is doing 300 "require_once", which turns into >100 ms. (ranking top position on my profiling case).

```
function smarty_modifier_date_format($string, $format = null, $default_date = '', $formatter = 'auto')
{
[...]
  require_once(SMARTY_PLUGINS_DIR . 'shared.make_timestamp.php');
[...]
}
```

Simple fix to go ~2 ms for 300 date_format calls:
```
function smarty_modifier_date_format($string, $format = null, $default_date = '', $formatter = 'auto')
{
  static $firsttime = 1;
  if ($firsttime === 1) {
    require_once(SMARTY_PLUGINS_DIR . 'shared.make_timestamp.php');
    $firsttime = 0;
  }
[...]
}
```

This also happens on some other modifiers.

**Comment by uwetews** [comment]
This is now fixed in the master branch

**Comment by sauliux** [comment]
Hi. Now we are receiving errors after this fix:

`array (
  'message' => 'Call to undefined function smarty_make_timestamp()',
  'file' => '/home/siteadmin/public_html/korys/lib/smarty/libs/plugins/modifier.date_format.php',
  'line' => 36,
)`

Maybe instead of require removal you should add this code:

`if (!is_callable('smarty_make_timestamp')) {
   require_once(SMARTY_PLUGINS_DIR . 'shared.make_timestamp.php');
}`

Thanks.

**Comment by uwetews** [comment]
Sorry, it should have been like that. it's now fixed
