### ISSUE TITLE
Why smarty use eval ()?

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [smarty-php/smarty#290]
Eval () function is dangerous for safety reasons should not be used. Eg.  https://insight.sensiolabs.com/what-we-analyse

How can I remove eval with the smart?

**Comment by mariuszkrzaczkowski** [comment]
eval is very slow 
http://php.webtutor.pl/en/2011/06/13/eval-counterparts-in-php-how-to-do-something-wrong-faster/

**Comment by uwetews** [comment]
Normally can load PHP code only from disc files be using PHP include or PHP require. Smarty does this for the compiled and cached template files which are PHP files. Other optional cache resource like memcache , mysql and others can it only in variables. So we must use eval here. It's safe as it executes exactly same code as the disk file.
Other use case is caused by an incompatibility of HHVM were a modified cached template can't be reloaded by same script.
Some other use cases are in the compiler which currently cant be avoided. here also speed is not an issue as you normally compile a template once.
eval() could be dangerous when not authorized users can access the variable containing the PHP code and manipulate it. There is very little chance the the user can do so as the code is generated by the Smarty compiler.
You should not worry about it.
