### ISSUE TITLE
Capture called by var - missing or illegal name attribute

### ISSUE THREAD

**Issue by luzel** [smarty-php/smarty#335]
Used to call capture by variable. After update not working.

{assign name="foo" value="custom_capture_name"}
{$smarty.capture[$foo]}

* Exception:
* Location: 
/smarty3/sysplugins/smarty_internal_templatecompilerbase.php 
 --> Smarty Compiler: Syntax error in template "file:/script_name.html"  on line 154 "{$smarty.capture[$foo]}" missing or illegal $smarty.capture name attribute <-- 

Problem is in smarty_internal_compile_capture.php:45 where in paremeter ends something like

Array ( [0] => 'capture' [1] => $_smarty_tpl->tpl_vars['foo']->value )

Parameters should look something like:

Array ( [0] => 'capture' [1] => 'custom_capture_name' )

PHP 7.0.8-0ubuntu0.16.04.3

**Comment by strikernl** [comment]
Used to work in 3.1.27, so seems to have broken in 3.1.28

**Comment by wisskid** [comment]
Could not reproduce, assuming you meant `{assign var="foo" value="custom_capture_name"}` instead of `{assign name="foo" value="custom_capture_name"}`. 
a
Anyhow, considering that there have been a number of fixes regarding capture issues and expressions since v3.1.28, I assume this has already been fixed. If not please submit a new bugreport with reproduction steps. Thank you!
