### ISSUE TITLE
From 3.1.27 to 3.1.28 broken html_options

### ISSUE THREAD

**Issue by va5ja** [smarty-php/smarty#340]
Version 3.1.27 works fine for me. If I update to 3.1.28 I have compilation problem with tag {html_options}.

`
Fatal error: Swiftlet\App::autoload(): Failed opening required 'Smarty/Internal/Compile/Html/Options.php' 

Smarty_Internal_TemplateCompilerBase->callTagCompiler( )	.../smarty_internal_templatecompilerbase.php:509
class_exists ( )	.../smarty_internal_templatecompilerbase.php:861
spl_autoload_call ( )	.../smarty_internal_templatecompilerbase.php:861
`

**Comment by kivisade** [comment]
This is probably the same issue I reported in #344. You can use my suggested solution (see pull request #345) as a temporary measure until this problem is fixed in master. There is only one line of code to be corrected, but you'll have to manually correct it every time you decide to upgrade your Smarty version, until this issue is fixed.

Hope this helps.

**Comment by uwetews** [comment]
This must be a problem of your autoloader. It should never try to load a not existing file but return false in such case. Otherwise class_exists() for not existing classes would always create errors.
The pull request #345  is just a workaround and reduces performance.

**Comment by uwetews** [comment]
See https://github.com/smarty-php/smarty/issues/344
