### ISSUE TITLE
{strip} doesn't remove white-spaces after comments {* *}

### ISSUE THREAD

**Issue by duzun** [smarty-php/smarty#447]
Here is an example:

```smarty
{strip}
    <br />
    {* some comment *}
    <br />
{/strip}
```
-> 
```html
<br />
    <br />
```

And there are some other edge cases around comments.

**Comment by peon501** [comment]
jeez all know this. Is this is problem to you :)

**Comment by wisskid** [comment]
This happens because smarty recognizes a newline directly following a comment as part of the comment and removes it. This is expected, since Smarty 2 would also do this. E.g.:
```
<tag1></tag1>
{* insightful comment *}
<tag2></tag2>
```
Is rendered as:
```
<tag1></tag1>
<tag2></tag2>
```
This, however causes the newline before the 4 spaces after the comment in de example above to have disappeared from the text content section. We can't take out any spaces at the beginning of a text content section, since that would remove inline spaces following a tag, e.g.:
```
{strip}{$amount}{if $showCurrency} EUR{if}{/strip}
```
would run together as
```
1337EUR
```
instead of the expected:
```
1337 EUR
```

Maybe we can merge consecutive text content sections before compiling them?

**Comment by duzun** [comment]
I understand this is an implementation detail.
But I see no semantic issue if strip would remove these spaces.
Merging consecutive text content sections before compiling them sounds reasonable.

In any case, this issue prevents me from commenting some parts of the templates. It is inconvenient.

**Comment by wisskid** [comment]
Could you test the branch in the linked Pull Request that I submitted yesterday? that should fix it.

**Comment by duzun** [comment]
Thank you @wisskid !
I've just updated smarty over composer and I see lots of spaces removed, just by upgrading!

If I find any issue or edge case, I'll let you know. It's been a while since I've posted this issue, thus I don't remember all the details.

This PR would definitely change the way we comment in smarty templates :)

**Comment by duzun** [comment]
ping @peon501

**Comment by duzun** [comment]
It looks great so far!
Can’t reproduce any of the issues related to comments any more.

**Comment by wisskid** [comment]
Thats good to hear. We noticed there are still issues with constructs such as;
```
{strip}
   {if $test} {* comment *}
        {$a = 3}
    {/if}
{/strip}
```

**Comment by peon501** [comment]
@duzun ty for ping I will check it later :)
