### ISSUE TITLE
isset variable variable error

### ISSUE THREAD

**Issue by ransom85** [smarty-php/smarty#456]
I have test for exists variable variable - {if isset($rfc822Name_err_{$key})}
For smarty verison 3.1.29 code works fine. But from version 3.1.30 generated php code cause error - Undefined index: rfc822Name_err_0.
PHP source coude for 3.1.29:
<?php if (isset($_smarty_tpl->tpl_vars['rfc822Name_err_'.($_smarty_tpl->tpl_vars['key']->value)]->value)) {
PHP source coude for 3.1.32:
<?php if ((($_smarty_tpl->tpl_vars['rfc822Name_err_'.($_smarty_tpl->tpl_vars['key']->value)]->value !== null ))) {

**Comment by chrisknerr** [comment]
I had the same phenomenon starting with Smarty 3.1.31 when using isset in a foreach or section loop and opened an issue about that here #453 - I think these two issues could be related because its also a var var situation.

Unfortunately I haven't found the source of that problem myself yet but I thought if you want to watch that maybe related issue too I link it for you here. 🙂

**Comment by wisskid** [comment]
This indeed seems to be a duplicate. See https://github.com/smarty-php/smarty/pull/567

**Comment by wisskid** [comment]
Duplicate of #453
