### ISSUE TITLE
{fetch} with https protocol

### ISSUE THREAD

**Issue by ackintosh** [smarty-php/smarty#465]
`{fetch}` allows us fetching external files via http/https.
In case of http protocol, [fsockopen() is used to fetch the content specified as "$params['file']"](https://github.com/smarty-php/smarty/blob/cc4d8fa1a07e18f00951a921041e37c87015dcb2/libs/plugins/function.fetch.php#L155-L157), but **https** is not.

The `if` statement below allows only http: 
https://github.com/smarty-php/smarty/blob/cc4d8fa1a07e18f00951a921041e37c87015dcb2/libs/plugins/function.fetch.php#L58

The file specified with **https** protocol can [be fetched with file_get_content()](https://github.com/smarty-php/smarty/blob/cc4d8fa1a07e18f00951a921041e37c87015dcb2/libs/plugins/function.fetch.php#L210), but ideally I think it should achieved with fsockopen() just like http.

Is there any reason that **https** is not allowed [here](https://github.com/smarty-php/smarty/blob/cc4d8fa1a07e18f00951a921041e37c87015dcb2/libs/plugins/function.fetch.php#L58)?

**Comment by wisskid** [comment]
Not a big fan of using `fsockopen` to handle all this http protocol stuff, but yes, https should work like http.

**Comment by wisskid** [comment]
Just realised we cannot do https using fsockopen, since we'd also have to do all the crypto handshakes etc... This cannot be done. As suggested in my previous comment, one might consider not using fsockopen for http too, but instead use a http client such as [guzzle](https://packagist.org/packages/guzzlehttp/guzzle#6.5.2) but guzzle isn't supported pre php5.5.
