### ISSUE TITLE
Get undefined property at smarty_internal_method_configload.php

### ISSUE THREAD

**Issue by tom-2015** [smarty-php/smarty#558]
Hi,

I updated to V3.1.33 today but I get error of undefined property Smarty::$smarty at line 176 when reading a configvariable that doesn't exist.

Changed line 176:
        if ( $data->smarty->error_unassigned && $errorEnable) {
to:
        if (isset($data->smarty) && $data->smarty!=null &&  $data->smarty->error_unassigned && $errorEnable) {

**Comment by wisskid** [comment]
There are unit test covering reading a config var that doesn't exist. See `\ConfigVarTest::testConfigUndefinedSilent` for example. I expect something else is going wrong. Also, this issue is quite old. If this is still an problem for you, please re-open this issue and submit a more elaborate reproduction scenario. Thank you!
