### ISSUE TITLE
[Discussion] Raising minimal supported PHP version

### ISSUE THREAD

**Issue by AnrDaemon** [smarty-php/smarty#593]
This is not the first time such question is raised, but until now it was more in the spirit of "if we raise Smarty, version, then…".

Now, I'd like to raise the reverse question. Should we actually KEEP supporting PHP5(for now), and for the future, which PHP versions we're supporting and how do we deal with version upgrades?

### Personal opinion following

As I see it right now, this is no longer a question of "which of PHP5 versions we support?" We can't keep support for 5.6 if we plan to have consistent error handling.

Here's a list of features I see relevant for Smarty as a project:

#### For 7.0:
 * [`\Throwable` interface](https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.error-handling.set-exception-handler);
 * [parsing exception](https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.error-handling.parse) (handle plugin loading failures better);
 * [AST parsing changes](https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling) may also be related for code generation;
 * [null coalescing operator](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op), while not specifically relevant, may prove invaluable for writing cleaner code;
 * [spaceship operator](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.spaceship-op) is of the same quality of life change;
 * [generator delegation](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.generator-delegation) may help in resolving `{foreach}` behavior with different kinds of `\Traversable`s.

#### For 7.1:
 * [`?nullable` types](https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types), [`iterable` pseudo-type](https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.iterable-pseudo-type) and [`void` return type](https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.void-functions);
 * [error exception on passing too few function arguments](https://www.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.too-few-arguments-exception);
 * [assignment via string index access on an empty string](https://www.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.empty-string-modifcation-by-character) may also be related as a major change in behavior.

#### For 7.4:
 * [allowed exceptions from `__toString()`](https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.tostring-exceptions) is imperative, but 7.4 is too high of a target right now.

There's a few things in 7.2 and 7.3 that can be considered QoL at best, but nothing I can call a major improvements or life-changer.

Given an increasing pressure from supporting disparate syntactic constructs between different PHP versions, the list of relevant features and consulting the list of [supported PHP versions](https://www.php.net/supported-versions), I think it would be reasonable to leave Smarty 3.1 targeting `PHP=^5.3.6 || ^7.0` (which would be a version bump from current 5.2, but will still probably work with 5.1+) and start a new Smarty version branch (3.2?) targeting `PHP=^7.1 || ^8.0` with maintained backward compatibility on template level.

The choice of version 5.3.6 is made because PHP up to this specific version received fixes to several facilities that I see important for consistent coding practices.

In addition, I think it may be worthwhile to start deprecation process for legacy Smarty2 constructs while we're still in compatibility mode.

**Comment by scottchiefbaker** [comment]
This seems like a reasonable scenario to me. Have a legacy Smarty branch that supports 5.x for as long we continue to support it.

Since we're looking at branching and supporting new version of PHP it might make sense to start clean with only 7.2+ (the only currently support PHP versions)?

**Comment by AnrDaemon** [comment]
Unless there's no major incentive to target specifically 7.2 ("currently supported" is not the one, backward compatibility is still a concern, and many enterprise systems would run "outdated" versions of PHP with only security patches for "stability" reasons), I don't see it as a good idea.

**Comment by scottchiefbaker** [comment]
Fair enough... it may make testing more difficult because we'll have to test with a bunch of outdated versions. It's a good goal to have if we can make it work.

**Comment by robo2bobo** [comment]
In my enterprise environment, we depend on redhat's long term support schedule. For example, CentOS 7 (and its PHP 5.4) has support up until 2024.

Everything we write, has the same end-of-life date as our underlying system, so everything we've done on CentOS 7, ends at 2024. Currently, we use CentOS 8, so what we do has an 7 or so year life span.

I've mentioned this before, but the kids who are not in a real corporate environment don't understand that an LTS linux distro gets coverage for PHP version, thus kids insisted that PHP 5.x is obsolete and couldn't understand that its not. Anyway, that issue was closed unfortunately.

I think a separate branch to offer security fixes for older versions is a good idea, while keeping the latest release fully implemented for modern PHP versions.

Thank you.

**Comment by wisskid** [comment]
I'm working on #629, planning to release it as Smarty 4.0, support PHP7.1 and up, including PHP8.0. 
7.1 is required, because we need "Void functions" to implement setUp/tearDown methods of PHPUnit 8. And we need PHPUnit 8 to be able to test for PHP8.

**Comment by wisskid** [comment]
Anyone here care to test #629 ?

**Comment by glensc** [comment]
If "void functions" is an argument, you can use phpunit-bridge to overcome the problem:
- https://symfony.com/doc/5.1/components/phpunit_bridge.html#removing-the-void-return-type

**Comment by wisskid** [comment]
@glensc that's interesting. So you're saying we could support PHP7.0 as well, then?

**Comment by AnrDaemon** [comment]
7.0 is a 5.x max. compat. release. There's no reason to support it, IMO.

**Comment by glensc** [comment]
@wisskid supporting only 7.0 is pointless, but keeping support for 7.0 and 5.x may have value. my personal recommendation is to go on with 4.x with newer PHP requirement and keep 3.x supported for older PHP versions.

**Comment by peon501** [comment]
Oh, dear.

**Comment by robo2bobo** [comment]
I agree that Smarty v4 should not come with the burden of old PHP versions below 7.2.

Enterprise servers running RHEL/CentOS 7 which still use PHP 5.4, have support until 2024. It should be ok for them to keep using Smarty v3.

Everyone else has moved on to PHP 7.2+, for example RHEL/CentOS 8.3 run 7.2 and 7.3. It is expected that future 8.4 releases will come with PHP 7.4. (btw, R.I.P. CentOS, redhat killed CentOS)

I am not aware of any system using PHP 7.0/7.1. Maybe someone would like to point them out?

In a year or so, everyone will be running PHP 8 by default (Fedora 35+) so please don't keep legacy code in Smarty v4.

**Comment by Bigbear7** [comment]
I also think that minimum Smarty version should be 7.2. When we migrated a 5.6 codebase to 7.x, the main issue was some PHP 7.2 aspects, like the https://wiki.php.net/rfc/counting_non_countables RFC. This RFC lead to another RFC in 7.3 to mitigate it, the https://wiki.php.net/rfc/is-countable RFC.

So I think it might be an advantage to not need to worry about having these kind of QOL issues at hand.

One could also argue that PHP 7.3 should be the minimum version given that 7.2 last release was 30/11 2020 or if one would like to take advantage on some of the really cool new features it could be 7.4.

**Comment by scottchiefbaker** [comment]
I think this is a good point to draw a line in the sand and only (officially) support PHP versions that are supported by the vendor.

PHP 7.2 is [end of life](https://www.php.net/supported-versions.php) as of last month. I like the idea of saying Smarty 4.x (or whatever Smarty.next is) is only supported on 7.3 and above. It may work on 7.1 or 7.2 but we don't fully test on older unsupported versions of PHP.

At the same time we can have the legacy Smarty 3.x branch for anyone that requires older PHP versions. Smarty 3.x moves to maintenance mode and only received security fixes?

**Comment by AnrDaemon** [comment]
Why not 8.0 then? There will always be incompatibilities, important fixes and other issues.

**Comment by glensc** [comment]
Setting the target too high, you may not able to reach it. For example, having 8.0 and not using its features is pointless, and rewriting to use 8.0 features will take too much effort that it would likely not be completed. Developers get tired and abandon the project. I think 7.2/7.3 is a big enough jump that allows moving forward right now and has useful language features that can be used. and also having too big a jump, makes the period longer that you need to support smarty3, because people are not able to move forward fast enough with newer PHP runtime requirements.

**Comment by Bigbear7** [comment]
Agree with staying on 7.x. One reason to go for  7.4 is that one could expect it to live quite long due to:
- It's a feature rich release, so it's quite attaractive.
- Going up to that version is not a huge hurdle if one have an 7.x compliant application, while going for 8.0 is a bigger step.
- It's the least release in the 7.x line.

But if not, 7.3 since the feature leap from 7.2 is not so big, meaning that migration aspects should be manageable.

Anyway, my experience with Smarty is that once I got it running on 7.0, it was never any big issue upgrading all the way up to 7.4. So had a very smooth upgrade path on the 7.x line, it was more like flipping a switch and off we go :-)

**Comment by wisskid** [comment]
Thank you all for your thoughts. I don't see much use in rewriting the code base just to "use new features", so there is no real advantage to dropping support for php7.x, as @glensc also noted.

I've looked through the migration guides - [7.2](https://www.php.net/manual/en/migration72.php) and [7.3](https://www.php.net/manual/en/migration73.php) and [7.4](https://www.php.net/manual/en/migration74.php) - and I see nothing that is crucial for Smarty. Also, unit tests are passing for php7.1, 7.2, 7.3, 7.4 and 8.0 in #629 so why bother dropping support for any of these versions? I don't think it's our job to force anyone out of using an "unsupported" PHP-version, someone may still be patching it for stability reasons, @AnrDaemon pointed out. If more libraries would try to be more backwards compatible, there would be less "dependency hell".

I'll continue by trying the fix for #617 suggested by @timmit-nl
Meanwhile, please put #629 to some more real world use.

**Comment by gnutix** [comment]
Any updates on #629 @wisskid ? Is a release going to happen anytime soon ? :)

**Comment by wisskid** [comment]
@gnutix no updates as of yet. Have you been able to test #629 ?

**Comment by gnutix** [comment]
I use this branch on a legacy project we upgraded to PHP 8.0. Seems to work alright, but still in the testing phase (not in production yet).

**Comment by Bigbear7** [comment]
I have tested it and started Smarty with: $smarty = new Smarty(); $smarty->setPHP7CompatMode(); etc

Now I get a lot of the following warnings like earlier:
-  Attempt to read property "value" on null
- Undefined array key

Now, I can fix it quick & dirty by  stating: $smarty->setErrorReporting(E_ALL & ~E_WARNING & ~E_NOTICE);

If the above warnings is due to app error or something in Smarty I haven't investigated. Still the production site runs flawlessly on PHP 7.4 with Smarty 3.1.38. So when running PHP 8 with Smarty it's mostly that the logs are flooded with warnings, my application works from what I can see.

Finally the name of fuction setPHP7CompatMode should probably bee setPHP8CompatMode since it's not needed at least for me to run Smarty with PHP 7.

**Comment by Bigbear7** [comment]
One code piece that flunks looks like compiled:
- <?php if ($_smarty_tpl->tpl_vars['myvariable']->value->myvalue == '') {?>

**Comment by gnutix** [comment]
@wisskid We're planning a production release for mid-August. Any chance there could be a stable release/tag by then ?

**Comment by wisskid** [comment]
OK, we're going to be dropping support for PHP7.0 and lower in Smarty4.
The setPHP7CompatMode method has been renamed due to popular demand :)
