### ISSUE TITLE
How to debug smarty v2?

### ISSUE THREAD

**Issue by grandeljay** [smarty-php/smarty#784]
I am maintaining a very old webshop currently running PHP 7.4 with smarty 2. As PHP 7.4 is EOL soon, I am trying to find out if I can somehow make it PHP 8 compatible to buy some time. 

In my development environment I have setup everything with PHP 8 and have fixed all PHP errors, warnings, notices, etc and most of the site seems to be working. Some pages however don't seem to load the template. I can only see the title and nothing else, as if smarty encountered a fatal error or similar. I have tried using `{debug}` and setting `debugging = true` but none of these settings seem to show any errors.

How can I find out what went wrong and further debug smarty?

**Comment by mohrt** [comment]
Did you clear out the compiled template and cached template folders after upgrading?

**Comment by grandeljay** [comment]
Yes, but I haven't noticed a difference.

**Comment by mohrt** [comment]
And PHP log files don't have errors?

**Comment by mohrt** [comment]
Smarty 2 is not compatible with PHP 8, if that is what you are trying to do.

**Comment by grandeljay** [comment]
> And PHP log files don't have errors?

Exactly, log files are completely empty.

> Smarty 2 is not compatible with PHP 8, if that is what you are trying to do.

That is what I am trying to do but shouldn't I be getting errors then? Is there maybe an option which suppresses them? It seems to just silently fail. I want to attempt to make smarty 2 PHP 8 compatible for my webshop - just as a temporary fix

**Comment by mohrt** [comment]
Short answer, it won't work. Getting Smarty 2 to work with PHP 8 would take a monumental undertaking, which is what Smarty 3 did. You'll have a lot less headache just updating to Smarty 3. There are basic guides how to do that bundled with Smarty 3.

**Comment by grandeljay** [comment]
Ok great, thanks!

What about breaking changes? All of the templates are written for Smarty 2, do I also need to rewrite all of them? Cause that's also a monumental undertaking.

Or do you think it's likely they will keep working?

**Comment by mohrt** [comment]
I would look at the upgrade notes, I know they come bundled in Smarty 3, not sure about 4.

**Comment by wisskid** [comment]
The changelog for v4.0.0 lists the things you might want to check, but it's mostly compatible.

- Dropped support for PHP7.0 and below, so Smarty now requires PHP >=7.1
- Dropped support for php asp tags in templates (removed from php since php7.0)
- Dropped deprecated API calls that where only accessible through SmartyBC
- Dropped support for {php} and {include_php} tags and embedded PHP in templates. Embedded PHP will now be passed through as is.
- Removed all PHP_VERSION_ID and compare_version checks and conditional code blocks that are now no longer required
- Dropped deprecated SMARTY_RESOURCE_CHAR_SET and SMARTY_RESOURCE_DATE_FORMAT constants
- Dropped deprecated Smarty::muteExpectedErrors and Smarty::unmuteExpectedErrors API methods
- Dropped deprecated $smarty->getVariable() method. Use $smarty->getTemplateVars() instead.
$smarty->registerResource() no longer accepts an array of callback functions
