### ISSUE TITLE
Alternative sprintf

### ISSUE THREAD

**Issue by bryxfr** [smarty-php/smarty#845]
What solution do you have for this:
{$smarty.config.trans_mail_contact|sprintf:$table.sujet:$table.nom:$table.mail:$table.ip:$[table.date](https://table.date/):$table.contenu}

Deprecated: Using php-function "sprintf" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in /home/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php on line 114

Thank you ^^

**Comment by wisskid** [comment]
"Use Smarty::registerPlugin to explicitly register a custom modifier."? 😃

**Comment by scottchiefbaker** [comment]
This gave me an excuse to teach myself something... here is the simple wrapper I came up with:

PHP:
```
$smarty->registerPlugin('modifier', 'smarty_sprintf', 'sprintf');
```

Template:
```
{"%s is %d years old"|smarty_sprintf:'Scott',99}
```

While this example DOES work, personally I would avoid it like the plague. If you're doing fancy `sprintf` stuff in your templates you might have a bigger problem. Unless it's really basic stuff, I would be processing all that data in PHP **before** it got to Smarty. Otherwise your templates are gonna be gnarly and hard to read.

**Comment by lecomteb27** [comment]
Thank you for your advice, I go directly through PHP instead of following Smarty's PHP fetch method for emails. Actually I am using a config file to manage languages and I needed this method in templates. Thank you, but why is this method abandoned by the Smarty development team?

**Comment by wisskid** [comment]
Smarty used to allow any PHP function as a function or modifier in templates. Whenever PHP changed function signatures, such as extra parameters or stricter type checking, we'd struggle to make workarounds to maintain backwards compatibility.

Also, this "passthru" approach opened Smarty up to significant security risks.

By limiting the default modifiers and functions, we clearly communicate what Smarty will maintain. If you need more, you can add plugins/extensions that you can maintain yourself.
