### ISSUE TITLE
5.0.0-rc1 is released as 4.3.3

### ISSUE THREAD

**Issue by timmit-nl** [smarty-php/smarty#905]
You can see it there: https://github.com/smarty-php/smarty/compare/v4.3.3...v5.0.0-rc1

And also in src/Smarty.php:
const SMARTY_VERSION = '5.0.0-rc1';

please pull the 4.3.3 release and make a 4.3.4 release of the 4.3.2, so the composer will work correctly!

**Comment by timmit-nl** [comment]
Also se the release here:

https://packagist.org/packages/smarty/smarty#v4.3.3

**Comment by ao1977** [comment]
Just noticed the same. Luckily, I was only deploying to my staging environment, which then died with a "Class 'Smarty' not found".

**Comment by wisskid** [comment]
I was cherry-picking a bugfix and accidentally tagged the wrong branch. 

I have removed the 4.3.3 tag from github and packagist and pushed a new, corrected 4.3.4 tag.

**Comment by matks** [comment]
Hello @wisskid,

What is the status of 4.3.4 tag?

Today I ran `composer update smarty/smarty-php` and Composer returned v4.3.4 for my project to use. However I can see the latest published GitHub release is 4.3.2

Is 4.3.4 a stable release? Can we use it? Because people who simply run `composer update` will start using it if it matches their Composer constraints (like `^4.3`)

**Comment by wisskid** [comment]
@matks I've marked the 4.3.4 tag as a proper Release just now.

**Comment by matks** [comment]
Thank you 👍
