### ISSUE TITLE
"Too many shorthand attributes" error message after migrated to smarty 5

### ISSUE THREAD

**Issue by rodriguezny** [smarty-php/smarty#949]
After migrated our project(Tiki Wiki CMS Groupware => [https://tiki.org/HomePage](https://tiki.org/HomePage) to smarty 5, I have the following error thrown in the template  [https://gitlab.com/tikiwiki/tiki/-/blob/master/templates/examples/search/related_tracker_items.tpl](https://gitlab.com/tikiwiki/tiki/-/blob/master/templates/examples/search/related_tracker_items.tpl) on line 5.

`Error: Syntax error in template "file:examples/search/related_tracker_items.tpl"  on line 5 "{if preg_match_all('/(.+?)\:([^\v]+)$/mis', $relationValue, $matches, 2)}" too many shorthand attributes`

Any idea of the mistake in my code ?
I explored some issues reported  in previous years about the same error message  "too many shorthand attribute" but none of them helped me, they are not similar to mine expect that they are both related to the use of the {if}{/if} block.

Below is the entire content of my template
<img width="1080" alt="image" src="https://github.com/smarty-php/smarty/assets/62137963/bb1bd22c-54f3-41d8-b778-3cb4f295cae5">

**Comment by wisskid** [comment]
The problem is caused by this call having 4 parameters... Somewhere while refactoring, I set `protected $shorttag_order = ['var1', 'var2', 'var3'];` to temporarily fix a bunch of problems, but I forgot to fix this properly. This went undetected as all unit tests use less than 4 parameters for function calls. This definitely needs a fix.

Also, Smarty5 does not seem to support passing parameters by reference anymore, as this code fragment does (the `$matches` parameter).

**Comment by wisskid** [comment]
@rodriguezny https://github.com/smarty-php/smarty/pull/953 should have fixed the 'too many shorthand attributes' error. Can you verify against smarty dev-master?

**Comment by rodriguezny** [comment]
Thanks @wisskid for the fix, I installed smarty dev-master, it works fine, the issue no longer exists.
